# -*- coding: utf-8 -*-
"""Sim_One.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ekdBihevreOuh52LDWRuZDYTbHEnekE

#Primeiro simulador de trânsito planetário da disciplina de Astrofísica Observacional

#Carrega Bibliotecas
"""

import numpy as np

"""#Execussão"""

''' Variables Declaration '''
# Fundamental constants
G = 6.6738 * 10**(-11)                                        # Gravitational constant (m^3 * kg^2 * s^(-2))
OneSec = 1.15741 * 10**(-5)                                   # One second in days
Gday = G/(OneSec**2)                                          # G constant in days

# Solar parameters
M_sun = 1.989 * 10**30                                        # Sun's mass in kg
R_sun = 6.957 * 10**8                                         # Planet's radius in m

# Input Parameters
R_star = R_sun                                                # Stellar radius in solar units
R_planet = 0.1 * (R_star/R_sun)                               # Fraction of solar radius (Earth radius = 0.00915 R_sun)
depth = (R_planet/R_star)**2                                  # Transit depth
P_orb = 5                                                     # Orbital period in days
ai = 90                                                       # Inclination angle of star (ranged over 0 and 90 degrees)
cadence = 0.020833                                            # Cadence in days (Kepler mission)
aa = ((Gday*M_sun/4/np.pi**2)*P_orb**2) ** (1/3)              # Major semi-axis (in m)
b = (aa/R_star) * np.cos(ai*np.pi/180)                        # Impact parameter (in a/R_star)

# Total time
part1 = R_star/aa
part2 = np.sqrt(((1 + R_planet/R_star)**2) - (b**2))
part3 = np.sqrt(((1 - R_planet/R_star)**2) - (b**2))

tTotal = (P_orb/np.pi) * (part1*part2) #np.arcsin(part1/(np.sin(ai))) * (part2**(1/2))
tF = (P_orb/np.pi) * (part1*part3)

tT_h = tTotal * 24

_sin = (R_star/aa) * (part2/(1-(np.cos(ai*np.pi/180)**2)))**(1/2)
k = P_orb/np.pi
tF = (P_orb/np.pi)*np.arcsin(_sin)